checks:
    python:
        code_rating: true
        duplicate_code: true
tools:
    pylint:
        python_version: '3'
        config_file: .pylintrc
filter:
    excluded_paths:
        - '*/tests/*'
        - '*/migrations/*'
build:
    environment:
        python: '3.5.0'
        variables:
            DJANGO_SETTINGS_MODULES: settings
            DATABASE_URL: postgres://scrutinizer:scrutinizer@localhost:5434/localized_fields
        postgresql: true

    dependencies:
        override:
            - 'pip install -r requirements/test.txt'
    tests:
        override:
            -
                command: pep8 ./localized_fields/
            -
                command: flake8 ./localized_fields/
            -
                command: coverage run manage.py test
                coverage:
                    file: '.coverage'
                    format: 'py-cc'
